/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.21.5
 * source: kex.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./common";
import * as pb_1 from "google-protobuf";
export namespace brewtheory {
    export class KeyExchangeRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            header?: dependency_1.brewtheory.RequestHeader;
            publicKey?: Uint8Array;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("header" in data && data.header != undefined) {
                    this.header = data.header;
                }
                if ("publicKey" in data && data.publicKey != undefined) {
                    this.publicKey = data.publicKey;
                }
            }
        }
        get header() {
            return pb_1.Message.getWrapperField(this, dependency_1.brewtheory.RequestHeader, 1) as dependency_1.brewtheory.RequestHeader;
        }
        set header(value: dependency_1.brewtheory.RequestHeader) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_header() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get publicKey() {
            return pb_1.Message.getFieldWithDefault(this, 2, new Uint8Array()) as Uint8Array;
        }
        set publicKey(value: Uint8Array) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            header?: ReturnType<typeof dependency_1.brewtheory.RequestHeader.prototype.toObject>;
            publicKey?: Uint8Array;
        }): KeyExchangeRequest {
            const message = new KeyExchangeRequest({});
            if (data.header != null) {
                message.header = dependency_1.brewtheory.RequestHeader.fromObject(data.header);
            }
            if (data.publicKey != null) {
                message.publicKey = data.publicKey;
            }
            return message;
        }
        toObject() {
            const data: {
                header?: ReturnType<typeof dependency_1.brewtheory.RequestHeader.prototype.toObject>;
                publicKey?: Uint8Array;
            } = {};
            if (this.header != null) {
                data.header = this.header.toObject();
            }
            if (this.publicKey != null) {
                data.publicKey = this.publicKey;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_header)
                writer.writeMessage(1, this.header, () => this.header.serialize(writer));
            if (this.publicKey.length)
                writer.writeBytes(2, this.publicKey);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): KeyExchangeRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new KeyExchangeRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.header, () => message.header = dependency_1.brewtheory.RequestHeader.deserialize(reader));
                        break;
                    case 2:
                        message.publicKey = reader.readBytes();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): KeyExchangeRequest {
            return KeyExchangeRequest.deserialize(bytes);
        }
    }
    export class KeyExchangeResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            header?: dependency_1.brewtheory.ResponseHeader;
            publicKey?: Uint8Array;
            token?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("header" in data && data.header != undefined) {
                    this.header = data.header;
                }
                if ("publicKey" in data && data.publicKey != undefined) {
                    this.publicKey = data.publicKey;
                }
                if ("token" in data && data.token != undefined) {
                    this.token = data.token;
                }
            }
        }
        get header() {
            return pb_1.Message.getWrapperField(this, dependency_1.brewtheory.ResponseHeader, 1) as dependency_1.brewtheory.ResponseHeader;
        }
        set header(value: dependency_1.brewtheory.ResponseHeader) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_header() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get publicKey() {
            return pb_1.Message.getFieldWithDefault(this, 2, new Uint8Array()) as Uint8Array;
        }
        set publicKey(value: Uint8Array) {
            pb_1.Message.setField(this, 2, value);
        }
        get token() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set token(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            header?: ReturnType<typeof dependency_1.brewtheory.ResponseHeader.prototype.toObject>;
            publicKey?: Uint8Array;
            token?: string;
        }): KeyExchangeResponse {
            const message = new KeyExchangeResponse({});
            if (data.header != null) {
                message.header = dependency_1.brewtheory.ResponseHeader.fromObject(data.header);
            }
            if (data.publicKey != null) {
                message.publicKey = data.publicKey;
            }
            if (data.token != null) {
                message.token = data.token;
            }
            return message;
        }
        toObject() {
            const data: {
                header?: ReturnType<typeof dependency_1.brewtheory.ResponseHeader.prototype.toObject>;
                publicKey?: Uint8Array;
                token?: string;
            } = {};
            if (this.header != null) {
                data.header = this.header.toObject();
            }
            if (this.publicKey != null) {
                data.publicKey = this.publicKey;
            }
            if (this.token != null) {
                data.token = this.token;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_header)
                writer.writeMessage(1, this.header, () => this.header.serialize(writer));
            if (this.publicKey.length)
                writer.writeBytes(2, this.publicKey);
            if (this.token.length)
                writer.writeString(3, this.token);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): KeyExchangeResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new KeyExchangeResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.header, () => message.header = dependency_1.brewtheory.ResponseHeader.deserialize(reader));
                        break;
                    case 2:
                        message.publicKey = reader.readBytes();
                        break;
                    case 3:
                        message.token = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): KeyExchangeResponse {
            return KeyExchangeResponse.deserialize(bytes);
        }
    }
}
